### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by VeinsOfSorrow** [brut0s/Uni-Brute.py#2]
We need to make each module a file, for example. We will have Uni-brute.py but lets say we plan on adding a built in scraper. Then we make the scraper as scraper.py and worry about integrating it with Uni-Brute later, so that way we can get all of the modules built and worry about making the product release ready later!

**Comment by brut0s** [comment]
i seee so like in the program cupp it has more then one python script in cahoots with the maine script, dont know how to do that though lol

**Comment by VeinsOfSorrow** [comment]
No, what it does is make all the modules separate files, for us to work on. Then later we are going to either keep them as modules [separate files] or combine them all into one file.
